// Mocks generated by Mockito 5.0.16 from annotations
// in ny_times_most_popular/test/ui/details/article_details_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ny_times_most_popular/domain/interactor/article_interactor.dart'
    as _i2;
import 'package:ny_times_most_popular/domain/model/article.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ArticleInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleInteractor extends _i1.Mock implements _i2.ArticleInteractor {
  MockArticleInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Article>> getArticles() =>
      (super.noSuchMethod(Invocation.method(#getArticles, []),
              returnValue: Future<List<_i4.Article>>.value(<_i4.Article>[]))
          as _i3.Future<List<_i4.Article>>);
  @override
  _i3.Future<void> refreshArticles() =>
      (super.noSuchMethod(Invocation.method(#refreshArticles, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i4.Article?> getArticleById(int? id) => (super.noSuchMethod(
      Invocation.method(#getArticleById, [id]),
      returnValue: Future<_i4.Article?>.value()) as _i3.Future<_i4.Article?>);
  @override
  String toString() => super.toString();
}
