// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhyX7WWlB64JWJYefCEdr2ULynz0_UTk',
    appId: '1:74287400164:web:4df438cc96d70a741dd8f1',
    messagingSenderId: '74287400164',
    projectId: 'flutterforumbme',
    authDomain: 'flutterforumbme.firebaseapp.com',
    storageBucket: 'flutterforumbme.appspot.com',
    measurementId: 'G-RLZCXMW8W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmR4v92SpydRKUjG2mJJcfIe7x0VRgtQ',
    appId: '1:74287400164:android:cd9deea82da75c981dd8f1',
    messagingSenderId: '74287400164',
    projectId: 'flutterforumbme',
    storageBucket: 'flutterforumbme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsMAVMatAGUW2EH5V2iMTbdnYd9Wnv-h0',
    appId: '1:74287400164:ios:a24e994c78b4bd101dd8f1',
    messagingSenderId: '74287400164',
    projectId: 'flutterforumbme',
    storageBucket: 'flutterforumbme.appspot.com',
    iosBundleId: 'hu.bme.auth.flutterforumbme.flutterForumBme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsMAVMatAGUW2EH5V2iMTbdnYd9Wnv-h0',
    appId: '1:74287400164:ios:a24e994c78b4bd101dd8f1',
    messagingSenderId: '74287400164',
    projectId: 'flutterforumbme',
    storageBucket: 'flutterforumbme.appspot.com',
    iosBundleId: 'hu.bme.auth.flutterforumbme.flutterForumBme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhyX7WWlB64JWJYefCEdr2ULynz0_UTk',
    appId: '1:74287400164:web:e4d9451df992f1001dd8f1',
    messagingSenderId: '74287400164',
    projectId: 'flutterforumbme',
    authDomain: 'flutterforumbme.firebaseapp.com',
    storageBucket: 'flutterforumbme.appspot.com',
    measurementId: 'G-CKHXJC61MH',
  );
}
