include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ############################################
    # CODE STYLING

    require_trailing_commas: true
    avoid_types_as_parameter_names: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    always_use_package_imports: true
    directives_ordering: true
    use_key_in_widget_constructors: true
    use_full_hex_values_for_flutter_colors: true
    prefer_foreach: true
    prefer_collection_literals: true
    sized_box_shrink_expand: true
    prefer_conditional_assignment: true
    use_if_null_to_convert_nulls_to_bools: true
    no_leading_underscores_for_local_identifiers: true
    no_leading_underscores_for_library_prefixes: true
    use_is_even_rather_than_modulo: true
    slash_for_doc_comments: true
    use_function_type_syntax_for_parameters: true
    type_literal_in_constant_pattern: true
    type_init_formals: true
    no_wildcard_variable_uses: true
    missing_code_block_language_in_doc_comment: true
    annotate_overrides: true
    prefer_null_aware_operators: true
    prefer_null_aware_method_calls: true
    prefer_is_not_operator: true
    prefer_is_not_empty: true
    prefer_is_empty: true
    prefer_initializing_formals: true
    prefer_if_null_operators: true
    prefer_generic_function_type_aliases: true
    non_constant_identifier_names: true 
    leading_newlines_in_multiline_strings: true
    eol_at_end_of_file: true
    curly_braces_in_flow_control_structures: true
    camel_case_types: true
    camel_case_extensions: true
    combinators_ordering: true
    deprecated_consistency: true
    file_names: true
    avoid_private_typedef_functions: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_escaping_inner_quotes: true

    ############################################
    # BASIC PERFORMANCE RULES

    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_decorated_box: true
    use_colored_box: true
    prefer_contains: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_constructors_over_static_methods: true
    avoid_slow_async_io: true

    ############################################
    # KEEPING IT CLEAN

    unnecessary_to_list_in_spreads: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    unnecessary_parenthesis: true
    unnecessary_overrides: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_aware_assignments: true
    unnecessary_new: true
    unnecessary_late: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    unnecessary_constructor_name: true
    unnecessary_const: true
    unnecessary_breaks: true
    unnecessary_brace_in_string_interps: true
    unnecessary_await_in_return: true
    use_named_constants: true
    no_logic_in_create_state: true
    only_throw_errors: true
    one_member_abstracts: true
    parameter_assignments: true
    prefer_spread_collections: true
    avoid_empty_else: true
    empty_statements: true
    no_adjacent_strings_in_list: true
    literal_only_boolean_expressions: true
    prefer_void_to_null: true
    always_declare_return_types: true
    prefer_mixin: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_function_declarations_over_variables: true
    prefer_asserts_in_initializer_lists: true
    no_literal_bool_comparisons: true
    exhaustive_cases: true
    empty_constructor_bodies: true
    empty_catches: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    join_return_with_assignment: true
    avoid_void_async: true
    avoid_unused_constructor_parameters: true
    avoid_types_on_closure_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_shadowing_type_parameters: true
    avoid_returning_this: true
    avoid_returning_null_for_void: true
    avoid_return_types_on_setters: true
    avoid_renaming_method_parameters: true
    avoid_redundant_argument_values: true
    avoid_positional_boolean_parameters: true
    avoid_null_checks_in_equality_operators: true
    avoid_implementing_value_types: true
    avoid_field_initializers_in_const_classes: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_double_and_int_checks: true
    
    ############################################
    # CORE RULES
    
    use_build_context_synchronously: true
    close_sinks: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    throw_in_finally: true
    overridden_fields: true
    type_annotate_public_apis: true
    tighten_type_of_initializing_formals: true
    test_types_in_equals: true

    ############################################
    # TRIVIAL STUFF THAT SHOULD NOT EVEN TRIGGER

    await_only_futures: true
    collection_methods_unrelated_type: true
    recursive_getters: true
    void_checks: true
    null_closures: true
    hash_and_equals: true
    unrelated_type_equality_checks: true
    no_duplicate_case_values: true
    no_self_assignments: true
    unnecessary_statements: true
    matching_super_parameters: true

    ############################################
    # BETTER SAFE THAN SORRY

    avoid_print: true
    avoid_web_libraries_in_flutter: true
    depend_on_referenced_packages: true
    provide_deprecation_message: true
    avoid_type_to_string: true
    valid_regexps: true
    implementation_imports: true
    conditional_uri_does_not_exist: true

    ############################################