# The files are generated into the path specified by `arb-dir`
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: L10n
nullable-getter: false # Force unwraps the of(context) getter in the generated class so that we don't have to use the null check operator in the code
