name: flutter_http
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  http: ^1.3.0
  weather_icons: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
